spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DATABASE}
      #      com.mongodb.MongoCommandException: Command failed with error 18 (AuthenticationFailed): 'Authentication failed.'  에러로 인해 잠시 제거
      username: root
      password: example
      authentication-database: admin
      auto-index-creation: true
logging:
  level:
    org:
      springframework:
        data:
          mongodb: info